
app:
  name: "friends"
  version: "0.0.1"

  development:
    server:

      httpPort: ":8080"

    database:

      address: "postgres:5432"
      username: "andrey"
      password: "andrey"
      nameDatabase: "database"
      dialect: postgres
      Datasource: "postgres://andrey:andrey@postgres:5432/database?sslmode=disable"
      dir: dirMigrite # Папка, где будут храниться файлы миграций
      table: migrations # Таблица для записи состояния миграций







