
app:
  name: "friends"
  version: "0.0.1"

  development:
    server:

      httpPort: ":8080"

    database:

      address: "postgres:5432"
      username: "andrey"
      password: "andrey"
      nameDatabase: "andrey"
      dialect: postgres
      Datasource: "postgres://andrey:andrey@postgres:5432/andrey?sslmode=disable"
      dir: dirMigrite
      table: migrations







