services:
  app:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - DB_HOST=andrey
        - DB_USER=andrey
        - DB_PASSWORD=andrey
        - DB_NAME=database
      ports:
          - "8080:8080"
      depends_on:
        postgres:
          condition: service_healthy
      networks:
          - my-network

  postgres:
      image: postgres:14-alpine
      environment:
        POSTGRES_DB: andrey
        POSTGRES_USER: andrey
        POSTGRES_PASSWORD: andrey
        PGDATA: /var/lib/postgresql/data
      volumes:
      - postgresql-data:/var/lib/postgresql
      ports:
        - "5432:5432"
      networks:
        - my-network
      healthcheck:
        test: [ "CMD", "pg_isready", "-U", "andrey" ]
        interval: 5s
        retries: 5

volumes:
  postgresql-data:

networks:
  my-network:
    driver: bridge
